import numpy as np
import pylab as pb
import sys
sys.path.append("../src")
import ssmodel, ideBase, ide, bases

def setup(kernel_weights = [.5,-0.3,.05]):
	dim=1
	space = np.arange(0,80,0.2)
	T=400
	obs_locns = np.linspace(0,80,10)
	min_field, max_field, inc = 0, 80, 8
	#Define field
	field_bases = [bases.gaussianBasis(dim,centre,5) for centre in np.arange(min_field,max_field+inc,inc)]
	field_weights = [0]*len(field_bases)
	field_weights[6] = 1
	f = ideBase.field(dim,field_bases,field_weights)
	#Define Kernel
	#--------------
	#This is the connectivity kernel
	kernel_bases = [bases.gaussianBasis(dim,0,1.8**2),bases.gaussianBasis(dim,0,6**2),bases.gaussianBasis(dim,0,18**2)] #Brain kernel
	#-------------------------------
	#This is  the kernel from Mike paper
	#------------------------------------------------------------------
	#kernel_bases = [bases.gaussianBasis(dim,centre,.1) for centre in [-.5,0,0.5]] 
	#kernel_weights =[-1,1,.5] 

	k = ideBase.kernel(dim,kernel_bases,kernel_weights)
	#noise
	ny = len(obs_locns)
	obs_noise_covariance =.2*np.eye(ny,ny)
	field_noise_variance =.8
	model=ide.ide(k,f,space,obs_locns,obs_noise_covariance,field_noise_variance,T,1)
	return model


def generate_observation(model):
	'''Generates observations and states from the model defined in setup'''
	model.gen_ssmodel()
	X,Y=model.simulate()
	return X,Y


def kernel_estimate(model):
	'''estimate the kernel using the observation generated by generate_observation'''
	X,Y=generate_observation(model)
	model.em(Y)
	
def plot_kernel(model, *args, **kwargs):
	'''plot the kernel'''
	u=np.linspace(-40,40,100)
	z=[]	
	for i in u:
		z.append(float(model.kernel.evaluate(i)))
	pb.plot(u,z, *args, **kwargs)
	
if __name__ == "__main__":
	
	# the weights correspond to three Gaussians.
	#Their variances are, respectively, [1.8, 6, 18]
	kernel_weights =[.5,-0.3,.05]
	# initialise and simulate the model
	model = setup()
	# plot the true kernel
	plot_kernel(model,'k-',lw=2)
	# estimate the kernel
	kernel_estimate(model)
	# plot the estimated kernel
	plot_kernel(model)
	# draw the graph
	pb.show()
